version: '3.6'

services:
    controller:
        container_name: controller
        hostname: controller
        image: controller:latest
        restart: always
        ports:
        - "8081:8081"
        volumes:
        - ./log:/var/log
