version: '3.6'
services:

  neo4j:
    image: fabrictestbed/neo4j-apoc:4.0.3
    container_name: broker-neo4j
    user: ${NEO4J_UID:-1000}:${NEO4J_GID:-1000}
    ports:
      - 8474:8474  # for HTTP
      - 8473:8473  # for HTTPS
      - 8687:8687  # for Bolt
    volumes:
      - ${NEO4J_DATA_PATH_HOST:-$(pwd)/neo4j/data}:${NEO4J_DATA_PATH_DOCKER:-/data}
      - ${NEO4J_IMPORTS_PATH_HOST:-$(pwd)/neo4j/imports}:${NEO4J_IMPORTS_PATH_DOCKER:-/imports}
      - ${NEO4J_LOGS_PATH_HOST:-$(pwd)/neo4j/logs}:${NEO4J_LOGS_PATH_DOCKER:-/logs}
      - ${NGINX_SSL_CERTS_DIR:-./ssl}/fullchain.pem:/ssl/neo4j.cert:ro  # SSL development certificate
      - ${NGINX_SSL_CERTS_DIR:-./ssl}/privkey.pem:/ssl/neo4j.key:ro     # SSL development key
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASS:-password}
      - NEO4J_dbms_connector_bolt_advertised__address=${NEO4J_dbms_connector_bolt_advertised__address:-localhost:7687}
      - NEO4J_dbms_connector_bolt_listen__address=${NEO4J_dbms_connector_bolt_advertised__address:-localhost:7687}
      - NEO4J_dbms_connector_http_advertised__address=${NEO4J_dbms_connector_http_advertised__address:-localhost:7474}
      - NEO4J_dbms_connector_http_listen__address=${NEO4J_dbms_connector_http_advertised__address:-localhost:7474}
      - NEO4J_dbms_connector_https_advertised__address=${NEO4J_dbms_connector_https_advertised__address:-localhost:7473}
      - NEO4J_dbms_connector_https_listen__address=${NEO4J_dbms_connector_https_advertised__address:-localhost:7473}
    networks:
      - broker
  database:
    image: fabrictestbed/postgres:12.3
    container_name: broker-db 
    restart: always
    environment:
       - POSTGRES_HOST=${POSTGRES_HOST:-database}
       - POSTGRES_PORT=5432
       - POSTGRES_DB=${POSTGRES_DB:-postgres}
       - POSTGRES_USER=${POSTGRES_USER:-postgres}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-broker}
    ports:
        - 9432:5432
    networks:
      - broker
  fabric-broker:
    image: broker:latest
    container_name: fabric-broker
    restart: always
    depends_on:
      - database
      - neo4j
    volumes:
        - "./config/config.broker.yaml:/etc/fabric/actor/config/config.yaml"
        - "./logs/broker:/var/log/actor"
        - "./secrets/snakeoil-ca-1-copy.crt:/etc/fabric/message_bus/ssl/cacert.pem"
        - "./secrets/kafkacat2.client.key:/etc/fabric/message_bus/ssl/client.key"
        - "./secrets/kafkacat2-ca1-signed.pem:/etc/fabric/message_bus/ssl/client.pem"
    networks:
      - orchestrator
networks:
  broker:
